name: Sample APP CI/CD
on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: davejfranco/codespace-app

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./app
      
      - name: Integration tests
        run: |
          npm test
        working-directory: ./app
      
      - name: Image version
        id: set-image
        run: echo "tag=$GITHUB_REF_NAME_$GITHUB_SHA" >> "GITHUB_OUTPUT"
    
    outputs:
      version: ${{ steps.set-image.outputs.tag }}
      
  
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker Build & Push
        run: |
          docker build -t $DOCKER_REPO:${{ needs.CI.outputs.version }} .
          docker push $DOCKER_REPO:${{ needs.CI.outputs.version }}
      
      