---
name: PR Check
on:
  pull_request:
    types:
      - opened

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          npm install
        working-directory: ./app
      
      - name: Run tests
        run: |
          npm test
        working-directory: ./app


      


