name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
      
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          title: ReleaseApp
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        run: echo "deploy!"